modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Avery Palermini"
displayURL="https://github.com/bentenavery/endrise"
updateJSONURL="https://raw.githubusercontent.com/bentenavery/endrise/main/update.json"
description='''
In the End, nothing is ever truly lost. Enderium ore and the tier above netherite, Soulbound gear that returns from death, a void that gives back, End masonry, Mourning Blooms, the graves of travelers who never made it home, and the Homeward Pearl that finally carries you back. Eight tides, one covenant.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
